### ISSUE TITLE
size选项的help问题 以及 gif每帧之间时间固定的问题

### ISSUE THREAD

**Issue by Flesh12138** [domgoer/jojogif#3]
`@click.option('--size', default='', help='the size of gif, width*height, ex: 500*500')`
提示是500*500但是实际应该是500x500才能识别，而且建议提示一下是x不是unicode

虽然新增了帧数的选择但是每帧之间的时间是固定的（貌似是沿用了之前10fps的标准么）
我看老兄你是算了每几帧取1帧，这样应该是可以算出来每帧之间的时间间隔的
`imageio.mimsave(outfilename, frames, 'GIF', duration = 算出来的数)`
另外这样还有可能（大概率）想要的帧数和实际帧数不符，增加一个提示或者换算出最后的帧率可能会好一些？

辛苦啦 :>

**Comment by domgoer** [comment]
sorry, 工作繁忙，没注意看。

>我看老兄你是算了每几帧取1帧，这样应该是可以算出来每帧之间的时间间隔的
imageio.mimsave(outfilename, frames, 'GIF', duration = 算出来的数)
另外这样还有可能（大概率）想要的帧数和实际帧数不符，增加一个提示或者换算出最后的帧率可能会好一些？

我觉得可以，👍
