### ISSUE TITLE
size自动减半的问题

### ISSUE THREAD

**Issue by Flesh12138** [domgoer/jojogif#4]
`frame = cv2.resize(
                        frame, (int(width * 0.5), int(height * 0.5)), interpolation=cv2.INTER_AREA)`
有这么一行还挺迷惑的
我有一个视频1280*720，就算我用了--size 1280x720最终结果也是640*360
不知道本意是想压缩体积吗？

**Comment by domgoer** [comment]
你是对的。
最早是不支持自定义大小的，后来加上那个功能，这里忘了改了。
赞👍！
