### ISSUE TITLE
有关2个小细节

### ISSUE THREAD

**Issue by Flesh12138** [domgoer/jojogif#7]
hi，我有2个地方不是很明白
一个是video.py里面貌似有很多try...finally...这种的，不是很清楚具体作用？网上貌似说try里面有return的话才会和别的地方不一样
还有一个是main.py里面的if __name__=='__main__"，既然这个作为一个包的话是不是就不用这2行了呢？
我理解错误的话请指正😄

**Comment by domgoer** [comment]
> 一个是video.py里面貌似有很多try...finally...这种的，不是很清楚具体作用？

`finally` 中做一些资源释放，比如临时文件删除。防止出现异常时临时文件不会被删除

> main.py里面的if name=='main"，既然这个作为一个包的话是不是就不用这2行了呢

这项目不是一个包，是可以被运行的

**Comment by Flesh12138** [comment]
直接运行的话没有结果吧
`if __name__ == "__main__":
    main()`
直接就是`error: path must not be None`

**Comment by domgoer** [comment]
`error: path must not be None` 这个就是运行结果呀

> main.py里面的if name=='main"，既然这个作为一个包的话是不是就不用这2行了呢

你是说将 

```
if __name__ == "__main__":
    main()
```

=>

```
main()
```

吗？

如果是这样的话，也是可以的，在这个项目里其实也没啥差别。

**Comment by Flesh12138** [comment]
没有，我想的是把这2行都去掉

**Comment by domgoer** [comment]
🤔emmm，那还是别了。还是要的

**Comment by Flesh12138** [comment]
哈哈哈虽然不明白为什么，但是听你的吧
